version: '3.8'

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: php-app
    restart: always
    working_dir: /var/www/
    volumes:
      - ../src:/var/www
  nginx-web:
    image: nginx:1.19-alpine
    container_name: nginx-web
    restart: always
    ports:
      - 80:80
    volumes:
      - ../src:/var/www
      - ./_config/_nginx:/etc/nginx/conf.d

  mysql-db:
    image: mariadb 
    container_name: mysql-db
    volumes:
        - dbdata:/var/lib/mysql
        - ./init:/docker-entrypoint-initdb.d
    hostname: mysql-db
    expose:
        - "3306"
    environment:
        MYSQL_USER: "db_admin"
        MYSQL_PASSWORD: "devmysql"
        MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
        MYSQL_DATABASE: mydb
        VIRTUAL_HOST: mysql.local
        VIRTUAL_PORT: 3306
    command: mysqld --sql_mode=""
    ports:
        - "31003:3306"

networks:
  default:
    name: app_main_network

volumes:
  dbdata: